name: Java Build

on:
  push:
    branches:
      - main  # 当 main 分支有代码推送时触发
  pull_request:
    branches:
      - main  # 当针对 main 分支的 Pull Request 被打开时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 作为运行环境

    steps:
    - uses: actions/checkout@v2  # 拉取代码到工作环境

    - name: Set up JDK 11  # 配置 JDK 环境
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven  # 使用 Maven 打包
      run: mvn -B package --file pom.xml  # 这里假设你的 pom.xml 文件在根目录下

    - name: Upload Jar File  # 上传生成的 JAR 文件（可选）
      uses: actions/upload-artifact@v2
      with:
        name: my-java-app
        path: target/*.jar  # 替换成实际生成的 JAR 文件路径
